name: monsalondz
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.7
  provider: ^6.0.4

  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar: ^5.0.2
  getwidget: ^3.0.1


  animated_custom_dropdown: 1.3.0
  flutter_localization: ^0.1.9
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.2.0
  url_launcher: ^6.1.8

  http: ^0.13.5
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/animation/
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-VariableFont_wght.ttf