name: monsalondz
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.1.1
  persistent_bottom_nav_bar: ^5.0.2
  getwidget: ^3.0.1
  lottie: ^2.0.0
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  animated_custom_dropdown: 1.3.0
  flutter_localization: ^0.1.9
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/svg/
    - assets/animation/
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
