name: monsalondz
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.11
  provider: ^6.0.5

  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar: ^5.0.2
  getwidget: ^3.1.1


  animated_custom_dropdown: ^1.5.0
  flutter_localization: ^0.1.10
  sqflite: ^2.2.8+2
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.3.2
  url_launcher: ^6.1.11
  photo_view: ^0.14.0

  http: ^0.13.6
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  maps_launcher: ^2.2.0
  checkbox_grouped: ^1.8.2
  location: ^4.4.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.6
  firebase_messaging: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/animation/
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-VariableFont_wght.ttf